/**
 * Follow-up suggestions shown after an answer.
 *
 * These are derived deterministically from the role and from the datasets the turn
 * actually used — never generated by the model. That keeps them free, instant, and
 * incapable of proposing something TrackAthlete cannot answer: if a dataset came back
 * empty we suggest a different direction rather than inviting the user to dig into
 * data that is not there.
 *
 * Each suggestion is just a pre-written user message and goes through the identical
 * validated, rate-limited pipeline as anything typed by hand.
 */

const MAX_SUGGESTIONS = 3;

/** Suggestions that make sense once a dataset has been shown, keyed by dataset. */
const AFTER_DATASET = {
  coachesOnPlatform: [
    { label: 'Send a request', prompt: 'How do I send a mentorship request to a coach, and what should I write in it?' },
    { label: 'Choosing a coach', prompt: 'What should I look for when choosing between coaches on TrackAthlete?' }
  ],
  academies: [
    { label: 'Verified vs listed', prompt: 'What is the difference between a verified academy and one that is only listed?' },
    { label: 'What to ask them', prompt: 'What should I ask an academy before joining, and what do the fee ranges cover?' }
  ],
  saiCentres: [
    { label: 'How to get in', prompt: 'How does admission to a SAI centre actually work, and who runs the trials?' },
    { label: 'Residential or not', prompt: 'What is the difference between residential and non-residential SAI schemes?' }
  ],
  tournaments: [
    { label: 'How to enter', prompt: 'How does tournament registration work, and does TrackAthlete handle it?' },
    { label: 'Build a record', prompt: 'How do I record my tournament results on my TrackAthlete profile?' }
  ],
  sportRecommendations: [
    { label: 'Why that score', prompt: 'Which rules contributed most to my top sport score, and what would raise it?' },
    { label: 'What it is not', prompt: 'Does a higher recommendation score mean my child will do better in that sport?' }
  ],
  federationStatus: [
    { label: 'Why it matters', prompt: 'Why does federation recognition matter for an athlete, in practical terms?' },
    { label: 'Last verified', prompt: 'What does the Last Verified date on federation information mean?' }
  ],
  sportsQuota: [
    { label: 'Eligibility', prompt: 'What achievement level do I usually need to qualify for a sports quota seat?' },
    { label: 'How to apply', prompt: 'How does a sports quota admission actually work, and who processes it?' }
  ],
  developmentRoadmap: [
    { label: 'The next stage', prompt: 'What does it take to move to the next stage of the roadmap?' },
    { label: 'What it costs', prompt: 'What are the realistic costs at each stage of this pathway?' }
  ],
  myConnections: [
    { label: 'Good session notes', prompt: 'What makes a useful session note, and how often should I add them?' },
    { label: 'Requests', prompt: 'How should I handle mentorship requests I cannot take on right now?' }
  ]
};

/** Where to steer when the platform had nothing to show for that dataset. */
const WHEN_EMPTY = {
  tournaments: { label: 'Other ways to compete', prompt: 'If TrackAthlete has no tournaments listed for my sport, how else can I find competitions to enter?' },
  sportsQuota: { label: 'Education pathways', prompt: 'How do sports quota and education pathways work in India generally?' },
  federationStatus: { label: 'How recognition works', prompt: 'How does sport recognition by a federation work in India?' },
  developmentRoadmap: { label: 'Typical progression', prompt: 'What does a typical district-to-state progression look like for my sport?' },
  academies: { label: 'Widen the search', prompt: 'If there are no academies listed near me, what are my options for training?' },
  coachesOnPlatform: { label: 'No coach yet', prompt: 'What can I work on by myself until I find a coach?' }
};

/** Fallbacks by role, used when a turn touched no dataset at all. */
const BY_ROLE = {
  athlete: [
    { label: 'My next step', prompt: 'What should I focus on next to progress in my sport?' },
    { label: 'Stronger profile', prompt: 'How can I make my athlete profile more attractive to coaches and sponsors?' },
    { label: 'Find a coach', prompt: 'How do I find and connect with a coach on TrackAthlete?' }
  ],
  parent: [
    { label: 'Compare sports', prompt: 'How do I compare sports for my child using the recommendation scores?' },
    { label: 'SAI pathways', prompt: 'What SAI centres and government pathways could my child aim for?' },
    { label: 'What it costs', prompt: 'What does a sports pathway typically cost at each stage?' }
  ],
  coach: [
    { label: 'My roster', prompt: 'How do I manage my athletes and mentorship requests on TrackAthlete?' },
    { label: 'Session notes', prompt: 'How do session notes work and what makes a useful one?' },
    { label: 'Be discoverable', prompt: 'How do athletes find me, and how do I make my coach profile stronger?' }
  ],
  sponsor: [
    { label: 'Find athletes', prompt: 'How do I find athletes seeking sponsorship on TrackAthlete?' },
    { label: 'What I can see', prompt: 'What information can I see about an athlete before sponsoring them?' },
    { label: 'How support works', prompt: 'How does recording sponsorship intent work on this platform?' }
  ],
  academy: [
    { label: 'Get verified', prompt: 'How does academy verification work and what does the badge mean?' },
    { label: 'Better listing', prompt: 'How do I keep my academy listing useful for parents and athletes?' },
    { label: 'Reach families', prompt: 'How do athletes and parents discover academies on TrackAthlete?' }
  ]
};

const GENERAL = [
  { label: 'How scoring works', prompt: 'How does the sport recommendation engine score a sport out of 100?' },
  { label: 'What "verified" means', prompt: 'What do verified, unverified and last verified mean across TrackAthlete?' },
  { label: 'What TrackAthlete does', prompt: 'What can I actually do on TrackAthlete?' }
];

/**
 * Loose similarity so we never suggest the question that was just asked.
 * Plurals are folded together — "session note" and "session notes" are the same
 * question, and missing that put a near-duplicate at the top of the list.
 */
function tooSimilar(prompt, message) {
  const words = (text) =>
    new Set(
      (String(text).toLowerCase().match(/[a-z]{4,}/g) || []).map((w) =>
        w.endsWith('ies') ? `${w.slice(0, -3)}y` : w.endsWith('s') && !w.endsWith('ss') ? w.slice(0, -1) : w
      )
    );
  const a = words(prompt);
  const b = words(message);
  if (!a.size) return false;
  let shared = 0;
  for (const w of a) if (b.has(w)) shared++;
  return shared / a.size > 0.5;
}

/**
 * @param {object} params
 * @param {string|null} params.role            authenticated role
 * @param {string} params.message              what the user just asked
 * @param {object} params.retrievedData        datasets from context.js (status per key)
 * @returns {Array<{label:string, prompt:string}>}
 */
function suggestFollowUps({ role, message = '', retrievedData = {} } = {}) {
  const picked = [];
  const seen = new Set();

  const add = (s) => {
    if (!s || picked.length >= MAX_SUGGESTIONS) return;
    if (seen.has(s.prompt) || tooSimilar(s.prompt, message)) return;
    seen.add(s.prompt);
    picked.push(s);
  };

  // Datasets that actually produced something lead the suggestions.
  for (const [key, value] of Object.entries(retrievedData)) {
    const status = value && value.status;
    if (status === 'ok') (AFTER_DATASET[key] || []).forEach(add);
    else if (status === 'empty' || status === 'not_applicable') add(WHEN_EMPTY[key]);
  }

  (BY_ROLE[role] || []).forEach(add);
  GENERAL.forEach(add);

  return picked.slice(0, MAX_SUGGESTIONS);
}

module.exports = { suggestFollowUps, MAX_SUGGESTIONS };
