import { useEffect, useState } from 'react';
import api from '../services/api';

const normalize = value => String(value || '').trim().toLowerCase();

export default function OrganizerEventsSection({ athleteSport }) {
  const [events, setEvents] = useState([]); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState('');
  useEffect(() => { api.get('/organizer-events/upcoming').then(({ data }) => setEvents(data.events || [])).catch(() => setNotice('Organizer events could not be loaded.')); }, []);
  async function register(event, sport) { setBusy(`${event._id}:${sport._id}`); setNotice(''); try { await api.post(`/organizer-events/${event._id}/register`, { sportConfigId: sport._id }); setNotice(`Registered for ${event.eventName} — ${sport.sportName}.`); } catch (err) { setNotice(err.response?.data?.error || 'Registration could not be completed.'); } finally { setBusy(''); } }
  if (!events.length && !notice) return null;
  return <section className="bg-[#fcfcf8] border border-[#d8ded5] rounded-2xl p-6 space-y-4"><div><p className="eyebrow" style={{ color: '#cc694e' }}>ORGANIZER EVENTS</p><h3 className="font-bold text-lg">Upcoming organizer events</h3></div>{notice && <p className="text-sm p-3 rounded bg-[#e2eee4]">{notice}</p>}<div className="grid gap-3">{events.map(event => <article key={event._id} className="border rounded-xl p-4 bg-white"><div className="flex justify-between gap-3"><div><span className="text-[10px] font-extrabold px-2 py-1 rounded bg-[#e2eee4] text-[#194e42]">ORGANIZER EVENT</span><h4 className="font-bold mt-2">{event.eventName}</h4><p className="text-xs text-[#526668]">{event.organizer?.organizationName || event.organizer?.name} · {event.venue} · {new Date(event.eventDate).toLocaleDateString('en-IN')}</p></div></div><div className="flex flex-wrap gap-2 mt-3">{event.sports.map(sport => { const eligible = normalize(sport.sportName) === normalize(athleteSport); const closed = new Date(event.registrationDeadline) < new Date(); return <div key={sport._id} className="border rounded-lg p-2 text-xs"><b className="text-[#194e42]">{sport.sportName.toUpperCase()}</b><div className="mt-1">{sport.feeType === 'free' ? 'Free' : `₹${sport.feeAmount || 0} · ${sport.feeType.replaceAll('_', ' ')}`}</div>{eligible && sport.competitionType === 'individual' && <button disabled={closed || busy === `${event._id}:${sport._id}`} onClick={() => register(event, sport)} className="mt-2 px-3 py-1 rounded bg-[#e07050] text-white font-bold disabled:opacity-50">{closed ? 'Registration closed' : busy ? 'Registering…' : 'Register'}</button>}{eligible && sport.competitionType === 'team' && <p className="mt-2 font-bold">Team registration available</p>}{!eligible && <p className="mt-2 text-[#697c7c]">Your sport is not eligible</p>}</div>; })}</div><p className="text-xs text-[#697c7c] mt-3">Registration deadline: {new Date(event.registrationDeadline).toLocaleDateString('en-IN')}</p></article>)}</div></section>;
}
